development:
  dialect: postgres
  database: example-web-app_development
  user: postgres
  password: 
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: example-web-app_test
  user: postgres
  password:
  host: 127.0.0.1

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/example-web-app_production"}}
